"""Generate morl_kernel.ts (baked pywt integral wavelet for 'morl') and reference CWT for verification."""
import base64
import json
import os
import sys

import numpy as np
import pywt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MORL_KERNEL_TS = os.path.join(ROOT, 'src', 'lib', 'morl_kernel.ts')


def bake_morl_kernel() -> None:
    """Bake the pywt morl integral wavelet (precision=12) as TS.

    pywt.cwt uses int_psi for the real-valued morl wavelet.
    """
    w = pywt.ContinuousWavelet('morl')
    int_psi, x = pywt.integrate_wavelet(w, precision=12)
    step = float(x[1] - x[0])
    span = float(x[-1] - x[0])
    # morl is real-valued, so int_psi is real
    int_psi_real = np.real(int_psi).astype('<f8')
    b64 = base64.b64encode(int_psi_real.tobytes()).decode('ascii')
    header = """// AUTO-GENERATED by scripts/gen_morl_kernel.py — do not edit by hand.
// int_psi = pywt.integrate_wavelet(pywt.ContinuousWavelet('morl'), precision=12)
// encoded as base64 of little-endian float64 (4096 values).
export const MORL_INT_PSI_B64 = %s
export const MORL_STEP = %r
export const MORL_SPAN = %r
""" % (json.dumps(b64), step, span)
    with open(MORL_KERNEL_TS, 'w', encoding='utf-8') as f:
        f.write(header)
    print('wrote', MORL_KERNEL_TS)


def make_morl_reference_scales() -> None:
    """Generate reference scales for morl wavelet at different configurations."""
    # Stage 1: scales 1-31, fs=100, n=1000
    scales_1 = np.arange(1, 32)
    # Stage 2: scales 1-48, fs=250, n=1250 (after downsample)
    scales_2 = np.arange(1, 49)

    print(f'Stage 1 scales ({len(scales_1)}): {scales_1[:5]}...{scales_1[-5:]}')
    print(f'Stage 2 scales ({len(scales_2)}): {scales_2[:5]}...{scales_2[-5:]}')


def make_morl_reference() -> None:
    """Reference pywt.cwt output for morl at fs=100, n=1000 (like HF model input)."""
    fs = 100.0
    n = 1000
    rng = np.random.default_rng(7)
    t = np.arange(n) / fs
    sig = (
        0.8 * np.exp(-((t - 1.2) % 1.0 - 0.0) ** 2 / (2 * 0.03 ** 2))
        + 0.25 * np.sin(2 * np.pi * 0.4 * t)
        + 0.03 * rng.standard_normal(n)
    ).astype(np.float32)

    scales = np.arange(1, 32)
    coef, _ = pywt.cwt(sig, scales, 'morl', sampling_period=1.0 / fs)
    mag = np.abs(coef)  # (31, 1000) float64

    out = {
        'sig': sig.tolist(),
        'scales': scales.tolist(),
        'mag': mag.tolist(),
    }
    ref_path = os.path.join(ROOT, 'scripts', 'cwt_morl_reference.json')
    with open(ref_path, 'w', encoding='utf-8') as f:
        json.dump(out, f)
    print(f'wrote {ref_path} mag max {float(mag.max()):.4f} mean {float(mag.mean()):.4f}')


def main() -> None:
    bake_morl_kernel()
    make_morl_reference_scales()
    make_morl_reference()


if __name__ == '__main__':
    sys.exit(main())
