"""Generate mexh_kernel.ts (baked pywt integral wavelet) and reference CWT for verification."""
import base64
import json
import math
import os
import sys

import numpy as np
import pywt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KERNEL_TS = os.path.join(ROOT, 'src', 'lib', 'mexh_kernel.ts')
REF_JSON = os.path.join(ROOT, 'scripts', 'cwt_reference.json')


def bake_kernel() -> None:
    int_psi, x = pywt.integrate_wavelet(pywt.ContinuousWavelet('mexh'), precision=12)
    assert int_psi.size == 4096 and x.size == 4096
    step = float(x[1] - x[0])
    span = float(x[-1] - x[0])  # 16.0
    b64 = base64.b64encode(int_psi.astype('<f8').tobytes()).decode('ascii')
    header = """// AUTO-GENERATED by scripts/gen_kernel.py — do not edit by hand.
// int_psi = pywt.integrate_wavelet(pywt.ContinuousWavelet('mexh'), precision=12)
// encoded as base64 of little-endian float64 (4096 values).
export const MEXH_INT_PSI_B64 = %s
export const MEXH_STEP = %r
export const MEXH_SPAN = %r
""" % (json.dumps(b64), step, span)
    with open(KERNEL_TS, 'w', encoding='utf-8') as f:
        f.write(header)
    print('wrote', KERNEL_TS)


def bake_cmor_kernel() -> None:
    """Bake the pywt complex cmor1.5-1.0 integral wavelet (precision=12) as TS.

    pywt.cwt conj()s int_psi for complex wavelets before building filters, so we
    bake the conjugated kernel here to avoid a runtime conj pass.
    """
    w = pywt.ContinuousWavelet('cmor1.5-1.0')
    int_psi, x = pywt.integrate_wavelet(w, precision=12)
    int_psi = np.conj(int_psi)
    step = float(x[1] - x[0])
    span = float(x[-1] - x[0])  # 16.0
    re_b64 = base64.b64encode(int_psi.real.astype('<f8').tobytes()).decode('ascii')
    im_b64 = base64.b64encode(int_psi.imag.astype('<f8').tobytes()).decode('ascii')
    scales = cmor_scales()
    header = """// AUTO-GENERATED by scripts/gen_kernel.py — do not edit by hand.
// int_psi = conj(pywt.integrate_wavelet(pywt.ContinuousWavelet('cmor1.5-1.0'), precision=12))
// encoded as base64 of little-endian float64 (4096 real + 4096 imag values).
export const CMOR_INT_PSI_RE_B64 = %s
export const CMOR_INT_PSI_IM_B64 = %s
export const CMOR_STEP = %r
export const CMOR_SPAN = %r
export const CMOR_SCALES = %s
""" % (json.dumps(re_b64), json.dumps(im_b64), step, span, json.dumps(scales.tolist()))
    with open(os.path.join(ROOT, 'src', 'lib', 'cmor_kernel.ts'), 'w', encoding='utf-8') as f:
        f.write(header)
    print('wrote src/lib/cmor_kernel.ts')


def cmor_scales() -> np.ndarray:
    """The 32 log-spaced scales used by Revised_HF_Non_HF.ipynb build_cwt_scales()."""
    cf = float(pywt.central_frequency(pywt.ContinuousWavelet('cmor1.5-1.0')))
    freqs = np.logspace(np.log10(40.0), np.log10(0.5), 32)
    return (cf * 100.0 / freqs).astype(np.float64)


def make_cmor_reference() -> None:
    """Reference pywt.cwt output for cmor1.5-1.0 at fs=100, n=1000 (like HF model input)."""
    fs = 100.0
    n = 1000
    rng = np.random.default_rng(7)
    t = np.arange(n) / fs
    sig = (
        0.8 * np.exp(-((t - 1.2) % 1.0 - 0.0) ** 2 / (2 * 0.03 ** 2))
        + 0.25 * np.sin(2 * np.pi * 0.4 * t)
        + 0.03 * rng.standard_normal(n)
    ).astype(np.float32)

    scales = cmor_scales()
    coef, _ = pywt.cwt(sig, scales, 'cmor1.5-1.0', sampling_period=1.0 / fs)
    mag = np.abs(coef)  # (32, 1000) float64

    out = {
        'sig': sig.tolist(),
        'scales': scales.tolist(),
        'mag': mag.tolist(),
    }
    with open(os.path.join(ROOT, 'scripts', 'cwt_cmor_reference.json'), 'w', encoding='utf-8') as f:
        json.dump(out, f)
    print('wrote scripts/cwt_cmor_reference.json mag max', float(mag.max()), 'mean', float(mag.mean()))


def make_filtfilt_reference() -> None:
    """Reference scipy.signal filtfilt output for the HF model bandpass.

    Matches apply_bandpass_filter from Revised_HF_Non_HF.ipynb:
      butter(4, [0.5/50, 40/50], btype='band')  (order-4 ba coefficients)
      filtfilt(b, a, sig) with default padtype='odd', padlen=None.
    The baked ba coefficients and reference outputs are stored for the TS parity check.
    """
    from scipy.signal import butter, filtfilt

    fs = 100.0
    nyq = 0.5 * fs
    b, a = butter(4, [0.5 / nyq, 40.0 / nyq], btype='band')
    rng = np.random.default_rng(11)
    n = 1000
    x = rng.standard_normal(n).astype(np.float32)
    y = filtfilt(b, a, x).astype(np.float64)

    out = {
        'b': b.tolist(),
        'a': a.tolist(),
        'x': x.tolist(),
        'y': y.tolist(),
    }
    with open(os.path.join(ROOT, 'scripts', 'filtfilt_reference.json'), 'w', encoding='utf-8') as f:
        json.dump(out, f)
    print('wrote scripts/filtfilt_reference.json y max', float(np.abs(y).max()))


def make_reference() -> None:
    fs = 250
    n = 2500
    rng = np.random.default_rng(123)
    t = np.arange(n) / fs
    sig = (
        0.8 * np.exp(-((t - 1.2) % 1.0 - 0.0) ** 2 / (2 * 0.03 ** 2))
        + 0.25 * np.sin(2 * np.pi * 0.4 * t)
        + 0.03 * rng.standard_normal(n)
    ).astype(np.float32)

    scales = np.arange(1, 33)
    coef, _ = pywt.cwt(sig, scales, 'mexh')
    mag = np.abs(coef)  # (32, 2500) float64

    out = {
        'sig': sig.tolist(),
        'mag': mag.tolist(),
    }
    with open(REF_JSON, 'w', encoding='utf-8') as f:
        json.dump(out, f)
    print('wrote', REF_JSON, 'mag max', float(mag.max()), 'mean', float(mag.mean()))


def main() -> None:
    bake_kernel()
    bake_cmor_kernel()
    make_reference()
    make_cmor_reference()
    make_filtfilt_reference()


if __name__ == '__main__':
    sys.exit(main())
