"""Generate mexh_kernel.ts (baked pywt integral wavelet) and reference CWT for verification."""
import base64
import json
import math
import os
import sys

import numpy as np
import pywt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KERNEL_TS = os.path.join(ROOT, 'src', 'lib', 'mexh_kernel.ts')
REF_JSON = os.path.join(ROOT, 'scripts', 'cwt_reference.json')


def bake_kernel() -> None:
    int_psi, x = pywt.integrate_wavelet(pywt.ContinuousWavelet('mexh'), precision=12)
    assert int_psi.size == 4096 and x.size == 4096
    step = float(x[1] - x[0])
    span = float(x[-1] - x[0])  # 16.0
    b64 = base64.b64encode(int_psi.astype('<f8').tobytes()).decode('ascii')
    header = """// AUTO-GENERATED by scripts/gen_kernel.py — do not edit by hand.
// int_psi = pywt.integrate_wavelet(pywt.ContinuousWavelet('mexh'), precision=12)
// encoded as base64 of little-endian float64 (4096 values).
export const MEXH_INT_PSI_B64 = %s
export const MEXH_STEP = %r
export const MEXH_SPAN = %r
""" % (json.dumps(b64), step, span)
    with open(KERNEL_TS, 'w', encoding='utf-8') as f:
        f.write(header)
    print('wrote', KERNEL_TS)


def make_reference() -> None:
    fs = 250
    n = 2500
    rng = np.random.default_rng(123)
    t = np.arange(n) / fs
    sig = (
        0.8 * np.exp(-((t - 1.2) % 1.0 - 0.0) ** 2 / (2 * 0.03 ** 2))
        + 0.25 * np.sin(2 * np.pi * 0.4 * t)
        + 0.03 * rng.standard_normal(n)
    ).astype(np.float32)

    scales = np.arange(1, 33)
    coef, _ = pywt.cwt(sig, scales, 'mexh')
    mag = np.abs(coef)  # (32, 2500) float64

    out = {
        'sig': sig.tolist(),
        'mag': mag.tolist(),
    }
    with open(REF_JSON, 'w', encoding='utf-8') as f:
        json.dump(out, f)
    print('wrote', REF_JSON, 'mag max', float(mag.max()), 'mean', float(mag.mean()))


def main() -> None:
    bake_kernel()
    make_reference()


if __name__ == '__main__':
    sys.exit(main())
